// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: paquete/paquete.proto

package paquete

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TipoCamion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo string `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
}

func (x *TipoCamion) Reset() {
	*x = TipoCamion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paquete_paquete_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipoCamion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipoCamion) ProtoMessage() {}

func (x *TipoCamion) ProtoReflect() protoreflect.Message {
	mi := &file_paquete_paquete_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipoCamion.ProtoReflect.Descriptor instead.
func (*TipoCamion) Descriptor() ([]byte, []int) {
	return file_paquete_paquete_proto_rawDescGZIP(), []int{0}
}

func (x *TipoCamion) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

type EstadoPaquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Estado string `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *EstadoPaquete) Reset() {
	*x = EstadoPaquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paquete_paquete_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoPaquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoPaquete) ProtoMessage() {}

func (x *EstadoPaquete) ProtoReflect() protoreflect.Message {
	mi := &file_paquete_paquete_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoPaquete.ProtoReflect.Descriptor instead.
func (*EstadoPaquete) Descriptor() ([]byte, []int) {
	return file_paquete_paquete_proto_rawDescGZIP(), []int{1}
}

func (x *EstadoPaquete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EstadoPaquete) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type PaqueteRecibido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo     string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor    int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Intentos int32  `protobuf:"varint,6,opt,name=intentos,proto3" json:"intentos,omitempty"`
	Estado   string `protobuf:"bytes,7,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *PaqueteRecibido) Reset() {
	*x = PaqueteRecibido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paquete_paquete_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaqueteRecibido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaqueteRecibido) ProtoMessage() {}

func (x *PaqueteRecibido) ProtoReflect() protoreflect.Message {
	mi := &file_paquete_paquete_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaqueteRecibido.ProtoReflect.Descriptor instead.
func (*PaqueteRecibido) Descriptor() ([]byte, []int) {
	return file_paquete_paquete_proto_rawDescGZIP(), []int{2}
}

func (x *PaqueteRecibido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaqueteRecibido) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *PaqueteRecibido) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *PaqueteRecibido) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

func (x *PaqueteRecibido) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type Paquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo     string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor    int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen   string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino  string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Intentos int32  `protobuf:"varint,6,opt,name=intentos,proto3" json:"intentos,omitempty"`
}

func (x *Paquete) Reset() {
	*x = Paquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paquete_paquete_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paquete) ProtoMessage() {}

func (x *Paquete) ProtoReflect() protoreflect.Message {
	mi := &file_paquete_paquete_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paquete.ProtoReflect.Descriptor instead.
func (*Paquete) Descriptor() ([]byte, []int) {
	return file_paquete_paquete_proto_rawDescGZIP(), []int{3}
}

func (x *Paquete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Paquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Paquete) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Paquete) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Paquete) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Paquete) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

type Orden struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Producto    string `protobuf:"bytes,2,opt,name=producto,proto3" json:"producto,omitempty"`
	Valor       int32  `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Tienda      string `protobuf:"bytes,4,opt,name=tienda,proto3" json:"tienda,omitempty"`
	Destino     string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
	Prioritario int32  `protobuf:"varint,6,opt,name=prioritario,proto3" json:"prioritario,omitempty"`
}

func (x *Orden) Reset() {
	*x = Orden{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paquete_paquete_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orden) ProtoMessage() {}

func (x *Orden) ProtoReflect() protoreflect.Message {
	mi := &file_paquete_paquete_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orden.ProtoReflect.Descriptor instead.
func (*Orden) Descriptor() ([]byte, []int) {
	return file_paquete_paquete_proto_rawDescGZIP(), []int{4}
}

func (x *Orden) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Orden) GetProducto() string {
	if x != nil {
		return x.Producto
	}
	return ""
}

func (x *Orden) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Orden) GetTienda() string {
	if x != nil {
		return x.Tienda
	}
	return ""
}

func (x *Orden) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Orden) GetPrioritario() int32 {
	if x != nil {
		return x.Prioritario
	}
	return 0
}

type OrdenRecibida struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OrdenRecibida) Reset() {
	*x = OrdenRecibida{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paquete_paquete_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdenRecibida) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdenRecibida) ProtoMessage() {}

func (x *OrdenRecibida) ProtoReflect() protoreflect.Message {
	mi := &file_paquete_paquete_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdenRecibida.ProtoReflect.Descriptor instead.
func (*OrdenRecibida) Descriptor() ([]byte, []int) {
	return file_paquete_paquete_proto_rawDescGZIP(), []int{5}
}

func (x *OrdenRecibida) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Seguimiento struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seguimiento string `protobuf:"bytes,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
}

func (x *Seguimiento) Reset() {
	*x = Seguimiento{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paquete_paquete_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seguimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seguimiento) ProtoMessage() {}

func (x *Seguimiento) ProtoReflect() protoreflect.Message {
	mi := &file_paquete_paquete_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seguimiento.ProtoReflect.Descriptor instead.
func (*Seguimiento) Descriptor() ([]byte, []int) {
	return file_paquete_paquete_proto_rawDescGZIP(), []int{6}
}

func (x *Seguimiento) GetSeguimiento() string {
	if x != nil {
		return x.Seguimiento
	}
	return ""
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_paquete_paquete_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_paquete_paquete_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_paquete_paquete_proto_rawDescGZIP(), []int{7}
}

func (x *Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_paquete_paquete_proto protoreflect.FileDescriptor

var file_paquete_paquete_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x2f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x22, 0x20, 0x0a, 0x0a, 0x74, 0x69, 0x70, 0x6f, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69,
	0x70, 0x6f, 0x22, 0x37, 0x0a, 0x0d, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x61, 0x71, 0x75,
	0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x7f, 0x0a, 0x0f, 0x70,
	0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69,
	0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x91, 0x01, 0x0a,
	0x07, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73,
	0x22, 0x9d, 0x01, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x69, 0x65, 0x6e, 0x64, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69,
	0x65, 0x6e, 0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x61, 0x72, 0x69, 0x6f,
	0x22, 0x2a, 0x0a, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x63, 0x69, 0x62, 0x69,
	0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x0b,
	0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x20, 0x0a,
	0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x32,
	0xdd, 0x02, 0x0a, 0x11, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x50,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x0e, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x6e, 0x1a, 0x17, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x61, 0x22, 0x00,
	0x12, 0x3f, 0x0a, 0x14, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x53, 0x65, 0x67,
	0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x14, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65,
	0x74, 0x65, 0x2e, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x1a, 0x0f,
	0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x2e, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22,
	0x00, 0x12, 0x3c, 0x0a, 0x11, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x50, 0x61,
	0x71, 0x75, 0x65, 0x74, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x2e, 0x74, 0x69, 0x70, 0x6f, 0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x1a, 0x10, 0x2e, 0x70, 0x61,
	0x71, 0x75, 0x65, 0x74, 0x65, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x22, 0x00, 0x12,
	0x47, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x45, 0x6e, 0x74, 0x72,
	0x65, 0x67, 0x61, 0x12, 0x18, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x2e, 0x70, 0x61,
	0x71, 0x75, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x6f, 0x1a, 0x17, 0x2e,
	0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x5f, 0x72, 0x65,
	0x63, 0x69, 0x62, 0x69, 0x64, 0x61, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x75,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x16, 0x2e, 0x70,
	0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x2e, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x61, 0x71,
	0x75, 0x65, 0x74, 0x65, 0x1a, 0x17, 0x2e, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x63, 0x69, 0x62, 0x69, 0x64, 0x61, 0x22, 0x00, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67,
	0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x54, 0x41, 0x52, 0x45, 0x41, 0x31, 0x53, 0x44, 0x2f, 0x4c, 0x6f,
	0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x61, 0x2f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_paquete_paquete_proto_rawDescOnce sync.Once
	file_paquete_paquete_proto_rawDescData = file_paquete_paquete_proto_rawDesc
)

func file_paquete_paquete_proto_rawDescGZIP() []byte {
	file_paquete_paquete_proto_rawDescOnce.Do(func() {
		file_paquete_paquete_proto_rawDescData = protoimpl.X.CompressGZIP(file_paquete_paquete_proto_rawDescData)
	})
	return file_paquete_paquete_proto_rawDescData
}

var file_paquete_paquete_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_paquete_paquete_proto_goTypes = []interface{}{
	(*TipoCamion)(nil),      // 0: paquete.tipoCamion
	(*EstadoPaquete)(nil),   // 1: paquete.estadoPaquete
	(*PaqueteRecibido)(nil), // 2: paquete.paqueteRecibido
	(*Paquete)(nil),         // 3: paquete.paquete
	(*Orden)(nil),           // 4: paquete.orden
	(*OrdenRecibida)(nil),   // 5: paquete.orden_recibida
	(*Seguimiento)(nil),     // 6: paquete.seguimiento
	(*Estado)(nil),          // 7: paquete.estado
}
var file_paquete_paquete_proto_depIdxs = []int32{
	4, // 0: paquete.logistica_cliente.EnviarPedido:input_type -> paquete.orden
	6, // 1: paquete.logistica_cliente.SolicitarSeguimiento:input_type -> paquete.seguimiento
	0, // 2: paquete.logistica_cliente.SolicitudPaquetes:input_type -> paquete.tipoCamion
	2, // 3: paquete.logistica_cliente.ResultadoEntrega:input_type -> paquete.paqueteRecibido
	1, // 4: paquete.logistica_cliente.ActualizarEstado:input_type -> paquete.estadoPaquete
	5, // 5: paquete.logistica_cliente.EnviarPedido:output_type -> paquete.orden_recibida
	7, // 6: paquete.logistica_cliente.SolicitarSeguimiento:output_type -> paquete.estado
	3, // 7: paquete.logistica_cliente.SolicitudPaquetes:output_type -> paquete.paquete
	5, // 8: paquete.logistica_cliente.ResultadoEntrega:output_type -> paquete.orden_recibida
	5, // 9: paquete.logistica_cliente.ActualizarEstado:output_type -> paquete.orden_recibida
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paquete_paquete_proto_init() }
func file_paquete_paquete_proto_init() {
	if File_paquete_paquete_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_paquete_paquete_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipoCamion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paquete_paquete_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoPaquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paquete_paquete_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaqueteRecibido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paquete_paquete_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paquete_paquete_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Orden); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paquete_paquete_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdenRecibida); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paquete_paquete_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seguimiento); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_paquete_paquete_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_paquete_paquete_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paquete_paquete_proto_goTypes,
		DependencyIndexes: file_paquete_paquete_proto_depIdxs,
		MessageInfos:      file_paquete_paquete_proto_msgTypes,
	}.Build()
	File_paquete_paquete_proto = out.File
	file_paquete_paquete_proto_rawDesc = nil
	file_paquete_paquete_proto_goTypes = nil
	file_paquete_paquete_proto_depIdxs = nil
}
